server:
  port: 8002
eureka:
  instance:
    # 服务端的实例名称
    hostname: eureka2.com
    metadata-map:
      version: 2.0
      xx: oo8002
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
    # 是否使用 readOnly缓存，默认开启
    use-read-only-response-cache: true
    # 多久更新一次只读缓存 默认 30 * 1000
    response-cache-update-interval-ms: 30000
    # 缓存过期时间 默认 180秒
    response-cache-auto-expiration-in-seconds: 180
  client:
    # 是否将自己注册到Eureka Server,默认为true，由于当前就是server，
    # 故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，表示自己就是注册中心， 我的职责是去维护服务实例，并不需要去检索服务,不需要调用其他服务
    fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流
    # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖的这个地址
    service-url:
      defaultZone: http://eureka1.com:8001/eureka/,http://eureka2.com:8002/eureka/,http://eureka3.com:8003/eureka/
spring:
  application:
    name: EurekaServer
