eureka:
  client:
    register-with-eureka: true
    #是否从eureka server获取注册信息，表示自己就是注册中心， 我的职责是去维护服务实例，并不需要去检索服务,不需要调用其他服务
    fetch-registry: true
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/
    # 定期拉取注册中心实例间隔时间，可优化成5秒，防止新服务上线，调用方获取不到新服务，默认30秒
    registry-fetch-interval-seconds: 5
    # 新服务注册延迟，默认40秒，可优化成 10秒，防止新服务没有马上被发现
    initial-instance-info-replication-interval-seconds: 10
  instance:
    # 心跳间隔,续约间隔 默认30秒
    lease-renewal-interval-in-seconds: 5
    # 超时时间，续约有效时间 默认90
    lease-expiration-duration-in-seconds: 90
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        url: http://localhost:8010

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        #      apiServerClient:
        #        connectTimeout: 3600000
        #        readTimeout: 3600000

# 熔断器配置
hystrix:
  dashboard:
    # http://localhost:8008/actuator/hystrix.stream 解决监控不到的问题
    proxy-stream-allow-list: localhost
  threadpool:
    default:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000
ribbon:
  # 连接超时时间，默认为1秒，该值会被FeignClient配置connectTimeout覆盖
  ConnectTimeout: 3000 #请求连接的超时时间
  # 读超时时间，默认为1秒，该值会被FeignClient配置readTimeout覆盖
  ReadTimeout: 5000 #请求处理的超时时间
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always